version: "3"

services:
    proxy:
        build: ./Proxy
        depends_on:
            - backend
        networks:
            - network1
        ports:
            - "443:443"
    
    backend:
        build: ./Backend
        depends_on:
            - database
        ports:
            - "2025:2025"
        networks:
            - network1
            - network2

    database:
        build: ./Database
        networks:
           - network2
        ports:
            - "3306:3306"

networks:
    network1:  
    network2:
