version: "3"
services:
    proxy:
        build: ./Proxy
        depends_on:
            - backend
        networks:
            - network1
        ports:
            - "443:443"
    
    backend:
        build: ./Backend
        depends_on:
            - database
        ports:
            - "5000:5000"
        networks:
            - network1
            - network2

    database:
        build: ./Database
        networks:
           - network2

networks:
 network1:
 network2:
