FROM python:3
ENV FLASK_APP opneksbackend.py
ENV FLASK_RUN_HOST 0.0.0.0

RUN pip3 install Flask
RUN pip3 install mysql-connector-python=latest

COPY opneksbackend.py opneksbackend.py
CMD [ "flask", "run" ]
